lzc-sdk-version: 0.1
package: cloud.lazycat.app.cloudbeaver
version: 24.3.0
name: cloudbeaver
description: 云数据库管理工具，支持 Mysql、Postgresql、Oracle、SQL Server 等多种数据库
license: https://choosealicense.com/licenses/mit/
homepage: https://github.com/dbeaver/cloudbeaver
author: dbaever
application:
  subdomain: cloudbeaver
  background_task: false
  routes:
    - /=http://cloudbeaver:8978
  ingress:
    - protocol: tcp
      port: 8978
      service: cloudbeaver
  depends_on:
    - cloudbeaver
services:
  cloudbeaver:
    image: registry.lazycat.cloud/zeroc/dbeaver/cloudbeaver:00c4de099c738d72
    binds:
      - /lzcapp/var/workspace:/opt/cloudbeaver/workspace
unsupported_platforms:
  - ios
  - android
