lzc-sdk-version: 0.1
name: minio
package: io.zeroc.app.minio
version: 0.0.1
description: MinIO是一个高性能、开源的对象存储服务器，兼容Amazon S3 API，旨在提供云原生应用的存储解决方案。
license: https://choosealicense.com/licenses/mit/
homepage: https://github.com/minio/minio
author: minio
application:
  subdomain: minio
  routes:
    - /=http://minio.io.zeroc.app.minio.lzcapp:9001
  public_path:
    - /manifest.json
  ingress:
    - protocol: tcp
      port: 9000
      service: minio
services:
  minio:
    image: registry.lazycat.cloud/zeroc/zeroc0077/minio:52e9d1ec895e4971
    binds:
      - /lzcapp/var/data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
